### ISSUE TITLE
HOTFIX needed

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/caproto#334]
Fix error reported by @tacaswell in #332, probably introduced in #329 and not seen because of ongoing Travis-CI random failure rate.

I can't immediately see what the problem is. It looks to me like the method is being passed the correct number of arguments.

```
self = <PV 'f4da4e39::permit', count=1, type=<ChannelType.TIME_ENUM: 17>, access=read/write>
    @ensure_connection
    def force_read_access_rights(self):
        'Force a read of access rights, not relying on last event callback.'
        self._access_rights_changed(self._caproto_pv.channel.access_rights,
>                                   forced=True)
E       TypeError: _access_rights_changed() missing 1 required positional argument: 'access_rights'
caproto/threading/pyepics_compat.py:502: TypeError
```

**Comment by danielballan** [comment]
Closed by #335
